// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: course.proto

package Course

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CourseListReq struct {
	// @inject_tag: binding:"required,oneof=10 20 30"
	Size_ int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty" binding:"required,oneof=10 20 30"`
	// @inject_tag: binding:"required,gte=1,lte=50"
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" binding:"required,gte=1,lte=50"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseListReq) Reset()         { *m = CourseListReq{} }
func (m *CourseListReq) String() string { return proto.CompactTextString(m) }
func (*CourseListReq) ProtoMessage()    {}
func (*CourseListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{0}
}
func (m *CourseListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseListReq.Unmarshal(m, b)
}
func (m *CourseListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseListReq.Marshal(b, m, deterministic)
}
func (m *CourseListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseListReq.Merge(m, src)
}
func (m *CourseListReq) XXX_Size() int {
	return xxx_messageInfo_CourseListReq.Size(m)
}
func (m *CourseListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CourseListReq proto.InternalMessageInfo

func (m *CourseListReq) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *CourseListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CourseModel struct {
	CourseId     int32   `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseName   string  `protobuf:"bytes,2,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CoursePrice  float32 `protobuf:"fixed32,3,opt,name=course_price,json=coursePrice,proto3" json:"course_price,omitempty"`
	CoursePrice2 float32 `protobuf:"fixed32,4,opt,name=course_price2,json=coursePrice2,proto3" json:"course_price2,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	Addtime              *TimeStamp `protobuf:"bytes,6,opt,name=addtime,proto3" json:"addtime,omitempty" gorm:"type:timestamp"`
	CourseIntr           string     `protobuf:"bytes,7,opt,name=course_intr,json=courseIntr,proto3" json:"course_intr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CourseModel) Reset()         { *m = CourseModel{} }
func (m *CourseModel) String() string { return proto.CompactTextString(m) }
func (*CourseModel) ProtoMessage()    {}
func (*CourseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{1}
}
func (m *CourseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseModel.Unmarshal(m, b)
}
func (m *CourseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseModel.Marshal(b, m, deterministic)
}
func (m *CourseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseModel.Merge(m, src)
}
func (m *CourseModel) XXX_Size() int {
	return xxx_messageInfo_CourseModel.Size(m)
}
func (m *CourseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseModel.DiscardUnknown(m)
}

var xxx_messageInfo_CourseModel proto.InternalMessageInfo

func (m *CourseModel) GetCourseId() int32 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *CourseModel) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *CourseModel) GetCoursePrice() float32 {
	if m != nil {
		return m.CoursePrice
	}
	return 0
}

func (m *CourseModel) GetCoursePrice2() float32 {
	if m != nil {
		return m.CoursePrice2
	}
	return 0
}

func (m *CourseModel) GetAddtime() *TimeStamp {
	if m != nil {
		return m.Addtime
	}
	return nil
}

func (m *CourseModel) GetCourseIntr() string {
	if m != nil {
		return m.CourseIntr
	}
	return ""
}

type CourseListResp struct {
	Courses              []*CourseModel `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	PageInfo             *PageInfo      `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseListResp) Reset()         { *m = CourseListResp{} }
func (m *CourseListResp) String() string { return proto.CompactTextString(m) }
func (*CourseListResp) ProtoMessage()    {}
func (*CourseListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{2}
}
func (m *CourseListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseListResp.Unmarshal(m, b)
}
func (m *CourseListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseListResp.Marshal(b, m, deterministic)
}
func (m *CourseListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseListResp.Merge(m, src)
}
func (m *CourseListResp) XXX_Size() int {
	return xxx_messageInfo_CourseListResp.Size(m)
}
func (m *CourseListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CourseListResp proto.InternalMessageInfo

func (m *CourseListResp) GetCourses() []*CourseModel {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *CourseListResp) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

type CourseDetailReq struct {
	// @inject_tag: uri:"course_id"
	CourseId int32 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty" uri:"course_id"`
	// @inject_tag: header:"req_type"
	ReqType              int32    `protobuf:"varint,2,opt,name=req_type,json=reqType,proto3" json:"req_type,omitempty" header:"req_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseDetailReq) Reset()         { *m = CourseDetailReq{} }
func (m *CourseDetailReq) String() string { return proto.CompactTextString(m) }
func (*CourseDetailReq) ProtoMessage()    {}
func (*CourseDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{3}
}
func (m *CourseDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDetailReq.Unmarshal(m, b)
}
func (m *CourseDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDetailReq.Marshal(b, m, deterministic)
}
func (m *CourseDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDetailReq.Merge(m, src)
}
func (m *CourseDetailReq) XXX_Size() int {
	return xxx_messageInfo_CourseDetailReq.Size(m)
}
func (m *CourseDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDetailReq proto.InternalMessageInfo

func (m *CourseDetailReq) GetCourseId() int32 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *CourseDetailReq) GetReqType() int32 {
	if m != nil {
		return m.ReqType
	}
	return 0
}

type CourseCount struct {
	// @inject_tag: json:"-"
	CountId int32 `protobuf:"varint,1,opt,name=count_id,json=countId,proto3" json:"-"`
	// @inject_tag: json:"-"
	CourseId             int32    `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"-"`
	CountKey             string   `protobuf:"bytes,3,opt,name=count_key,json=countKey,proto3" json:"count_key,omitempty"`
	CountValue           int64    `protobuf:"varint,4,opt,name=count_value,json=countValue,proto3" json:"count_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCount) Reset()         { *m = CourseCount{} }
func (m *CourseCount) String() string { return proto.CompactTextString(m) }
func (*CourseCount) ProtoMessage()    {}
func (*CourseCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{4}
}
func (m *CourseCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCount.Unmarshal(m, b)
}
func (m *CourseCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCount.Marshal(b, m, deterministic)
}
func (m *CourseCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCount.Merge(m, src)
}
func (m *CourseCount) XXX_Size() int {
	return xxx_messageInfo_CourseCount.Size(m)
}
func (m *CourseCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCount.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCount proto.InternalMessageInfo

func (m *CourseCount) GetCountId() int32 {
	if m != nil {
		return m.CountId
	}
	return 0
}

func (m *CourseCount) GetCourseId() int32 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *CourseCount) GetCountKey() string {
	if m != nil {
		return m.CountKey
	}
	return ""
}

func (m *CourseCount) GetCountValue() int64 {
	if m != nil {
		return m.CountValue
	}
	return 0
}

type CourseDetailResp struct {
	CourseDetail         *CourseModel   `protobuf:"bytes,1,opt,name=courseDetail,proto3" json:"courseDetail,omitempty"`
	CourseCounts         []*CourseCount `protobuf:"bytes,2,rep,name=course_counts,json=courseCounts,proto3" json:"course_counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseDetailResp) Reset()         { *m = CourseDetailResp{} }
func (m *CourseDetailResp) String() string { return proto.CompactTextString(m) }
func (*CourseDetailResp) ProtoMessage()    {}
func (*CourseDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{5}
}
func (m *CourseDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDetailResp.Unmarshal(m, b)
}
func (m *CourseDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDetailResp.Marshal(b, m, deterministic)
}
func (m *CourseDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDetailResp.Merge(m, src)
}
func (m *CourseDetailResp) XXX_Size() int {
	return xxx_messageInfo_CourseDetailResp.Size(m)
}
func (m *CourseDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDetailResp proto.InternalMessageInfo

func (m *CourseDetailResp) GetCourseDetail() *CourseModel {
	if m != nil {
		return m.CourseDetail
	}
	return nil
}

func (m *CourseDetailResp) GetCourseCounts() []*CourseCount {
	if m != nil {
		return m.CourseCounts
	}
	return nil
}

func init() {
	proto.RegisterType((*CourseListReq)(nil), "Course.CourseListReq")
	proto.RegisterType((*CourseModel)(nil), "Course.CourseModel")
	proto.RegisterType((*CourseListResp)(nil), "Course.CourseListResp")
	proto.RegisterType((*CourseDetailReq)(nil), "Course.CourseDetailReq")
	proto.RegisterType((*CourseCount)(nil), "Course.CourseCount")
	proto.RegisterType((*CourseDetailResp)(nil), "Course.CourseDetailResp")
}

func init() { proto.RegisterFile("course.proto", fileDescriptor_ad75674299e1bb1e) }

var fileDescriptor_ad75674299e1bb1e = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0xda, 0xa1, 0x69, 0x6f, 0x3a, 0xcc, 0x60, 0x04, 0x98, 0xb2, 0xa0, 0x84, 0x4d, 0x25,
	0xa0, 0x8b, 0xb0, 0x18, 0x24, 0x96, 0x33, 0x02, 0x45, 0x3c, 0x34, 0xca, 0x54, 0x6c, 0xa3, 0xd0,
	0x5c, 0x50, 0x44, 0x63, 0xbb, 0xb6, 0x3b, 0x52, 0xd9, 0x22, 0x7e, 0x80, 0x3f, 0xe4, 0x4f, 0x90,
	0xed, 0x38, 0x24, 0xa8, 0xcc, 0xce, 0x3e, 0xf7, 0xdc, 0xd7, 0x39, 0x36, 0x4c, 0xd7, 0x7c, 0x27,
	0x15, 0x2e, 0x85, 0xe4, 0x9a, 0x93, 0xd1, 0xb9, 0xbd, 0xcd, 0xa6, 0x6b, 0x5e, 0xd7, 0x9c, 0x39,
	0x34, 0x3e, 0x83, 0x63, 0x87, 0xbf, 0xaf, 0x94, 0xce, 0x70, 0x4b, 0x08, 0x1c, 0xa9, 0xea, 0x3b,
	0xd2, 0x60, 0x1e, 0x2c, 0x6e, 0x65, 0xf6, 0x6c, 0x30, 0x51, 0x7c, 0x45, 0x3a, 0x70, 0x98, 0x39,
	0xc7, 0xbf, 0x03, 0x88, 0x5c, 0xe6, 0x07, 0x5e, 0xe2, 0x86, 0x3c, 0x82, 0x89, 0x6b, 0x97, 0x57,
	0x65, 0x93, 0x3c, 0x76, 0x40, 0x5a, 0x92, 0xc7, 0x10, 0x35, 0x41, 0x56, 0xd4, 0xae, 0xce, 0x24,
	0x03, 0x07, 0x7d, 0x2c, 0x6a, 0x24, 0x4f, 0xfc, 0xb0, 0xb9, 0x90, 0xd5, 0x1a, 0xe9, 0x70, 0x1e,
	0x2c, 0x06, 0x59, 0x93, 0x74, 0x69, 0x20, 0xf2, 0x14, 0x8e, 0xbb, 0x94, 0x84, 0x1e, 0x59, 0xce,
	0xb4, 0xc3, 0x49, 0xc8, 0x33, 0x08, 0x8b, 0xb2, 0xd4, 0x55, 0x8d, 0x74, 0x34, 0x0f, 0x16, 0x51,
	0x72, 0x67, 0xe9, 0x86, 0x5c, 0xae, 0xaa, 0x1a, 0xaf, 0x74, 0x51, 0x8b, 0xcc, 0x33, 0x3a, 0x53,
	0x55, 0x4c, 0x4b, 0x1a, 0x76, 0xa7, 0x4a, 0x99, 0x96, 0x71, 0x0d, 0xb7, 0xbb, 0xe2, 0x28, 0x41,
	0x5e, 0x40, 0xe8, 0xe2, 0x8a, 0x06, 0xf3, 0xe1, 0x22, 0x4a, 0xee, 0xfa, 0xfa, 0x1d, 0x2d, 0x32,
	0xcf, 0x21, 0xcf, 0x61, 0x6c, 0xc4, 0x4a, 0xd9, 0x17, 0x6e, 0x97, 0x8e, 0x92, 0x53, 0xcf, 0xbf,
	0x6c, 0xf0, 0xac, 0x65, 0xc4, 0x29, 0x9c, 0xb8, 0xe0, 0x05, 0xea, 0xa2, 0xda, 0x18, 0x37, 0x6e,
	0x54, 0xf5, 0x21, 0x8c, 0x25, 0x6e, 0x73, 0xbd, 0x17, 0xde, 0x9a, 0x50, 0xe2, 0x76, 0xb5, 0x17,
	0x18, 0xff, 0x68, 0xdd, 0x39, 0xe7, 0x3b, 0xa6, 0x0d, 0x75, 0x6d, 0x0e, 0x7f, 0xcb, 0x84, 0xf6,
	0x9e, 0x96, 0xfd, 0x16, 0x83, 0x7f, 0x5a, 0xb8, 0x20, 0xd3, 0xf9, 0x37, 0xdc, 0x5b, 0x53, 0x26,
	0x99, 0x2b, 0xf4, 0x0e, 0xf7, 0x8d, 0x7e, 0x4c, 0xe7, 0xd7, 0xc5, 0x66, 0x87, 0xd6, 0x8f, 0xa1,
	0xd5, 0x8f, 0xe9, 0x4f, 0x06, 0x89, 0x7f, 0x06, 0x70, 0xda, 0xdf, 0x48, 0x09, 0x72, 0xe6, 0xad,
	0x76, 0x98, 0x1d, 0xe7, 0x3f, 0x3a, 0xf6, 0x88, 0xe4, 0x55, 0xfb, 0x00, 0x6c, 0x0b, 0x45, 0x07,
	0x87, 0x1c, 0xb0, 0xfb, 0xfa, 0x4c, 0x7b, 0x51, 0xc9, 0xaf, 0xc0, 0xbf, 0xf2, 0x2b, 0x94, 0xd7,
	0xe6, 0x31, 0xbd, 0x06, 0x30, 0x9e, 0xbe, 0xe1, 0x72, 0xc5, 0x05, 0xb9, 0xd7, 0x2f, 0xd1, 0x7c,
	0x85, 0xd9, 0xfd, 0x43, 0xb0, 0x12, 0xe4, 0x02, 0x4e, 0xde, 0xa2, 0xee, 0x2e, 0x46, 0x1e, 0xf4,
	0xa9, 0xad, 0x81, 0x33, 0x7a, 0x38, 0xa0, 0xc4, 0xe7, 0x91, 0xfd, 0x80, 0x2f, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x52, 0xb6, 0x07, 0xa6, 0x03, 0x00, 0x00,
}
